apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo-demo
type: Opaque
data:
  # FIXME: those are not real secrets change them locally!
  mongo-root-username: dGVzdA==
  mongo-root-password: dGVzdA==
