# This play should only be run by the 'main' node of the cluster.

- name: check if  all the node have a running microk8s
  command: "microk8s status"
  register: cluster_status
  failed_when: "('microk8s is running' not in cluster_status.stdout)"

- name: ip for node
  debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
  # with_items: "{{ groups['cluster_leaf'] }}"

- name:
  set_fact:
    is_joined: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'] in cluster_status.stdout }}"

- name: is_joined
  debug:
    msg: "Is: {{is_joined}}"

- name: request joining token from the first main node
  delegate_to: "{{ groups['cluster_main'][0] }}"
  command: microk8s add-node
  register: joining_token
  when: "{{ not is_joined and inventory_hostname in groups['cluster_leaf']}}"
  failed_when: "('microk8s join' not in joining_token.stdout)"

- name: joining_token
  debug:
    msg: "Token {{ joining_token['stdout_lines'][1] }}"
  when: "{{ not is_joined and inventory_hostname in groups['cluster_leaf']}}"

- name: join cluster as cluster_leaf
  command: "{{ joining_token['stdout_lines'][1] }}"
  register: joining_output
  when: "{{ not is_joined and inventory_hostname in groups['cluster_leaf']}}"

- name: joining_output
  debug:
    msg: "Join finished with: {{ joining_output }}"