# This play should only be run by the 'main' node of the cluster.

- name: create cluster as cluster_main
  command: microk8s add-node
  register: joining_tokens
  with_items: "{{ groups['cluster_leaf'] }}"
# We have to do this for each unjoined 'leaf' node.
  when: "{{inventory_hostname in groups['cluster_main']}}"

# output is like this
# ....
# "stdout_lines": [
#   "From the node you wish to join to this cluster, run the following:",
#   "microk8s join 192.168.0.241:25000/b45ea7ec9fee481a0fba08e22c86795c",
#   "",
#   "If the node you are adding is not reachable through the default interface you can use one of the following:",
#   " microk8s join 192.168.0.241:25000/b45ea7ec9fee481a0fba08e22c86795c",
#   " microk8s join 192.168.0.13:25000/b45ea7ec9fee481a0fba08e22c86795c",
#   " microk8s join 10.1.93.192:25000/b45ea7ec9fee481a0fba08e22c86795c"
# ],
# ...

- name: join cluster as cluster_leaf
  command: "{{ item['stdout_lines'][1] }}"
  register: joining_outputs
  delegate_to: "{{ item['item'] }}"
  with_items: "{{ joining_tokens.results }}"
  when: "{{inventory_hostname in groups['cluster_main']}}"

- name: debug output of joining
  debug:
    msg: "Join finished with: {{ joining_outputs }}"