# This play should be run every node that should join the cluster.
# This play book might be a little unstable...

- name: check if all the node have a running microk8s
  command: "microk8s status"
  register: cluster_status
  failed_when: "('microk8s is running' not in cluster_status.stdout)"

- name: request a token
  command: microk8s add-node
  register: tokens
  when: "inventory_hostname in groups['cluster_main'] and hostvars[item]['ansible_default_ipv4']['address'] not in cluster_status.stdout "
  loop: "{{groups['cluster_leaf']}}"

- name: join cluster as cluster_leaf
  delegate_to: "{{ item.item }}"
  command: "{{ item.stdout_lines[1] }}"
  register: joining_outputs
  when: "inventory_hostname in groups['cluster_main'] and hostvars[item.item]['ansible_default_ipv4']['address'] not in cluster_status.stdout"
  loop: "{{tokens.results}}"

- name: debug joing outpu
  debug:
    msg: "OUTPUT {{ joining_outputs }}"
