- name: install snapd
  become: yes
  apt:
    name: snapd
    update_cache: yes
    state: present

- name: install microk8s
  become: yes
  snap:
    name: microk8s
    state: present
    classic: yes
    channel: latest/stable

# sudo usermod -a -G microk8s $USER
- name: add user to microk8s group
  become: yes
  user:
    name: vato
    append: yes
    groups: microk8s

- name: set permissions on .kube dir
  become: yes
  file:
    path: ~/.kube/
    state: directory
    recurse: yes
    owner: vato
    group: vato

# reset connection so the usermod kicks in
# su - $USER
- name: reset ssh connection
  meta: reset_connection

# microk8s status --wait-ready
- name: wait for microk8s
  command: microk8s status --wait-ready
  register: microk8s_status
  failed_when: "('microk8s is running' not in microk8s_status.stdout)"

- name: debug the status
  debug:
    msg: "Status: {{ microk8s_status }}"

  # microk8s config > config
- name: get kubeconfig
  delegate_to: rasp4-one
  command: microk8s config
  register: microk8s_config_output

- name: create .kube config
  copy:
    content: "{{ microk8s_config_output.stdout }}"
    dest: ~/.kube/config
    force: no
    mode: 0600