- name: install snapd
  apt:
    name: snapd
    update_cache: yes
    state: present

- name: install microk8s
  become: yes
  snap:
    name: microk8s
    state: present
    classic: yes
    channel: latest/stable

# sudo usermod -a -G microk8s $USER
- name: add user to microk8s group
  user:
    name: vato
    append: yes
    groups: microk8s

# reset connection so the usermod kicks in
# su - $USER
- name: reset ssh connection
  meta: reset_connection

# microk8s status --wait-ready
- name: wait for microk8s
  command: microk8s status --wait-ready
  # command: microk8s status
  register: microk8s_status
  failed_when: "('microk8s is running' not in microk8s_status.stdout)"
