#!/usr/bin/env ansible-playbook
---
# this playbook will shutdown all hosts good night

- name: shutdown all hosts
  become: true
  hosts: "all"
  gather_facts: no
  tasks:

  - name: down the remote nodes
    community.general.shutdown:
