#!/usr/bin/env ansible-playbook
---
# this playbook will shutdown all hosts good night

- hosts: all
  become: true
  gather_facts: no
  tasks:

  - name: shut down the node
    community.general.shutdown:
      delay: 60
